<a href="https://colab.research.google.com/github/amoukrim/Python/blob/main/Week3/ExerciseXP/Exercisew3d1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 1 : Array Creation and Manipulation

In [1]:
import numpy as np
#Create a 1D NumPy array containing numbers from 0 to 9.
array1d = np.arange(10)
print (array1d)

[0 1 2 3 4 5 6 7 8 9]


Exercise 2 : Type Conversion and Array Operations

In [7]:
# Convert to NumPy array and change data type to integer
liste =  [3.14, 2.17, 0, 1, 2]

array = np.array(liste).astype(int)

# affichage
print(array)


[3 2 0 1 2]


Exercise 3 : Working with Multi-Dimensional Arrays

In [8]:
# Create array from 1 to 9 and reshape to 3x3
array  = np.arange(1,10)

array_3x3 = array.reshape(3, 3)

# Display the result
print(array_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


import random
Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
#Create a 2D NumPy array of shape (4, 5) filled with random numbers.




In [11]:
# 1ère méthode
#Create the array
array = np.random.rand(4, 5)

# Round the array values to 2 decimal places for readability
random_array = np.round(array, 2)

print(random_array)

[[0.87 0.58 0.85 0.10 0.18]
 [0.53 0.33 0.20 0.53 0.94]
 [0.11 0.34 0.60 0.45 0.38]
 [0.58 0.50 0.69 0.00 0.29]]


In [12]:
# 2ème méthode
#Create a 4x5 array with random numbers between 0 and 1
np.set_printoptions(precision=2, floatmode='fixed')  # Force 2 décimales
random_array = np.round(np.random.rand(4, 5), 2)
print(random_array)

[[0.36 0.30 0.31 0.02 0.08]
 [0.08 0.21 0.98 0.85 0.22]
 [0.08 0.25 0.76 0.35 0.49]
 [0.22 0.76 0.96 0.44 0.19]]


Exercise 5 : Indexing Arrays


In [14]:
#Select the second row from a given 2D NumPy array.
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print ("array", array)
secondrow = array[1]
print ("secondrow", secondrow)

array [[21 22 23 22 22]
 [20 21 22 23 24]
 [21 22 23 22 22]]
secondrow [20 21 22 23 24]


Exercise 6 : Reversing elements

In [16]:
# Given array
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reverse the array
reversed_arr = arr[::-1]  # Slicing with step -1 reverses the array

print(reversed_arr)

# Alternative Methods: Using np.flip()
reversed_arr2 = np.flip(arr)
print(reversed_arr2)


[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


Exercise 7 : Identity Matrix
Create a 4x4 identity matrix using NumPy.

In [ ]:
#Create a 4x4 identity matrix using NumPy.

identity_matrix = np.eye(4)  # Creates a 4x4 identity matrix
print(identity_matrix)
#The diagonal elements are 1 and All other elements are 0.

Exercise 8 : Simple Aggregate Funcs
Find the sum and average of a given 1D array.

In [18]:
# Given array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Calculate sum and average

total_sum = np.sum(arr)  # other Alternative: total_sum = arr.sum()
average = np.mean(arr)   # other Alternative: average = total_sum / len(arr)

print(f"Sum : {total_sum}, Average : {average}")

Sum: 45, Average: 5.0


Exercise 9 : Create Array and Change its Structure
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [ ]:
array = np.arange(1, 21)   # Generates [1, 2, ..., 20]
print("array", array)
# Reshape into a 4x5 matrix
matrix_4x5 = array.reshape(4,5)

#print the result
print("matrix_4x5", matrix_4x5)

Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.


In [28]:
#given array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_numbers = array[array % 2 != 0]
print("odd_numbers", odd_numbers)